SistemaPedidos/SistemaPedidos/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaPedidos.Models;

namespace SistemaPedidos.Controllers
{
    public class ClientesController : Controller
    {
        PedidosContext context;

        public ClientesController(PedidosContext _context)
        {
            context = _context;
        }
    
        public async Task<IActionResult> Index()
        {
            var customers = await context.Clientes.ToListAsync();
            Cliente cli = new Cliente();
            ViewBag.clientes = customers;
            return View(cli);
        }
        [BindProperty]
        public Cliente cli3 { get; set; }
        public async Task<IActionResult> NuevoCliente()
        {
            var id= cli3.IdCliente;
            var _cliente = await context.Clientes.Where(x => x.IdCliente == cli3.IdCliente).AnyAsync();

            if (!_cliente)
            {
                context.Clientes.Add(cli3);
            }
            else
            {
                context.Clientes.Attach(cli3);
                context.Entry(cli3).State = EntityState.Modified;

            }
            await context.SaveChangesAsync();
            return Redirect("Index");
        }

        public async Task<IActionResult> Modificar(int id)
        {
            var cus = await context.Clientes.FindAsync(id);
            if (cus == null)
                return RedirectToAction("Index");

            return View(cus);
        }

        public async Task<IActionResult> Eliminar(int id)
        {
            var cliDelete = await context.Clientes.FindAsync(id);

            if (cliDelete == null)
            {
                return StatusCode(404);
            }
            else
                context.Clientes.Remove(cliDelete);
            context.SaveChanges();
            return Redirect("/Clientes/");
        }
    }

    
}

SistemaPedidos/SistemaPedidos/Controllers/DireccionesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaPedidos.Models;
using System;
using System.Linq;

namespace SistemaPedidos.Controllers
{
    public class DireccionesController : Controller
    {
        PedidosContext context;
        public DireccionesController(PedidosContext _context)
        {
            context = _context;
        }
  
        public async Task<IActionResult> Index()
        {

            var idsClientes = await context.Venta.Where(v=>v.Pagado ==false).Select(v=>v.IdCliente).Distinct().ToListAsync();

            var cusDir = await context.Clientes.Where(x=>idsClientes.Contains(x.IdCliente)).Select(x => new {x.IdCliente,NombreCliente = x.Nombre +"  "+x.Apellido}).ToListAsync();

           var dir = await context.Direccions.Where(z=>z.Entregado == false).Include(x => x.IdClienteNavigation).OrderBy(z=>z.Horario).ToListAsync();
            Direccion direc = new Direccion();
            ViewBag.Direccion = dir;
            ViewBag.CliDire = cusDir;
            return View(direc);
        }
        [BindProperty]
        public Direccion direccion { get; set; }
        public async Task<IActionResult> Nuevo()
        {
            var NewDir = await context.Direccions.Where(x => x.IdDireccion == direccion.IdDireccion).AnyAsync();

            if(!NewDir)
            {
                context.Direccions.Add(direccion);
            }else
            {
                context.Direccions.Attach(direccion);
                context.Entry(direccion).State = EntityState.Modified;
            }
            await context.SaveChangesAsync();
            return Redirect("Index");
        }

        public async Task<IActionResult> Modificar(int id)
        {
            var cus = await context.Clientes.Select(x => new { x.IdCliente, NombreCliente = x.Nombre + "  " + x.Apellido }).ToListAsync();
            var dir = await context.Direccions.FindAsync(id);
            ViewBag.Customers = cus;
            if (dir == null)
                return RedirectToAction("Index");

            return View(dir);
        }
        public async Task<IActionResult> Eliminar(int id)
        {
            var dir = await context.Direccions.FindAsync(id);

            if (dir == null)
                return StatusCode(404);
            else
            {
                context.Direccions.Remove(dir);
                context.SaveChanges();
                return Redirect("/Direcciones/");
            }
        }

        public async Task<IActionResult> Entregado(int id)
        {
            var Entregas = await context.Direccions.FindAsync(id);

            if (Entregas != null)
            {
                Entregas.Entregado = true;
                await context.SaveChangesAsync();
            }

            return Redirect("/Direcciones/");
        }
    }
}

SistemaPedidos/SistemaPedidos/Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaPedidos.Models;
using System.Globalization;
using static System.Collections.Specialized.BitVector32;

namespace SistemaPedidos.Controllers
{
    public class ProductosController : Controller
    {
        PedidosContext context;

        public ProductosController(PedidosContext _context)
        {
            context = _context;
        }

        public async Task<IActionResult> Index()
        {
            var marcas = await context.Marcas.ToListAsync();
            var Prod = await context.Productos.Include(x => x.IdMarcaNavigation).ToListAsync();
            Producto Product = new Producto();
            ViewBag.Productos = Prod;
            ViewBag.Marcas = marcas;
            return View(Product);
        }
        [BindProperty]
        public Producto Prod1 { get; set; }
        public async Task<IActionResult> AgregarProducto()
        {
            var prod = await context.Productos.Where(x => x.IdProducto == Prod1.IdProducto).AnyAsync();
            var _producto = await context.Productos.FindAsync(Prod1.IdProducto);
            if (_producto == null)
            {

                context.Productos.Add(Prod1);
            }

            else
            {



                double.TryParse(Prod1.PrecioCompra.ToString(), out double precioDecimal);
                var formato = new CultureInfo("es-AR");
                formato.NumberFormat.CurrencySymbol = "$";
                formato.NumberFormat.CurrencyDecimalSeparator = ",";
                formato.NumberFormat.CurrencyGroupSeparator = ".";
                CultureInfo.DefaultThreadCurrentCulture = formato;
                CultureInfo.DefaultThreadCurrentUICulture = formato;



                //var precio = precioDecimal.ToString("N1");
                _producto.Nombre = Prod1.Nombre;
                _producto.IdMarca = Prod1.IdMarca;
                _producto.Color = Prod1.Color;
                _producto.Modelo = Prod1.Modelo;
                _producto.Talle = Prod1.Talle;
                _producto.Descripcion = Prod1.Descripcion;
                _producto.PrecioCompra = Prod1.PrecioCompra;
                _producto.Precio = Prod1.Precio;
                _producto.Stock = Prod1.Stock;
                //context.Productos.Attach(Prod1);
                //context.Entry(Prod1).State = EntityState.Modified;
            }
            await context.SaveChangesAsync();
            return Redirect("Index");
        }
        public async Task<IActionResult> Modificar(int id)
        {
            var marcas1 = await context.Marcas.ToListAsync();
            var producto = await context.Productos.FindAsync(id);
            ViewBag.Marcas1 = marcas1;
            if (producto == null)
                return RedirectToAction("Index");

            return View(producto);
        }

        public async Task<IActionResult> Eliminar(int id)
        {
            var Product = await context.Productos.FindAsync(id);

            if (Product == null)
                return StatusCode(404);
            else
            {
                context.Productos.Remove(Product);
                context.SaveChanges();
                return Redirect("/Productos/");
            }
        }
    }
}

SistemaPedidos/SistemaPedidos/Controllers/VentasController.cs
using Azure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaPedidos.Models;
using System.Data.SqlClient;
namespace SistemaPedidos.Controllers
{
    public class VentasController : Controller
    {
        PedidosContext context;
        Models.Response res = new Models.Response();
        public VentasController(PedidosContext _context)
        {
            context = _context;
        }
        public async Task<IActionResult> Index()
        {
           
            var vent = await context.Venta.Include(r=>r.Pedidos).Include(x => x.IdClienteNavigation).Include(t=>t.IdTipoNavigation).ToListAsync();
            Ventas xvent = new Ventas();          
            ViewBag.Ventas = vent;
        
            //Tuple<Ventas, Pedido> Model = new Tuple<Ventas, Pedido>(Venta, new Pedido());
            return View(xvent);
        }
        [BindProperty]
        public Ventas venta { get; set; }
  
        public async Task<IActionResult> Nuevo(int? id)
        {
            var valor = id;
            var _vent = await context.Venta.FindAsync(id);
            var Venta = new Ventas();
            if (_vent != null)
            {
                Venta = _vent;
            }
            var cust = await context.Clientes.ToListAsync();
            var tipo = await context.Tipos.ToListAsync();
            ViewBag.Tipos = tipo;
            ViewBag.Clientes = cust;

            var prodd = await context.Productos.Where(x=>x.Stock > 0).Select(x => new { x.IdProducto, NombreProducto = x.Nombre + " - " + x.IdMarcaNavigation.Nombre + " - " +x.Talle}).ToListAsync();
            
            ViewBag.Productos = prodd;
            if (id != null)
                ViewBag.Pedido = await context.Pedidos.Include(p => p.IdProductoNavigation).Where(x => x.IdVenta == id.Value).ToListAsync();
            Tuple<Ventas, Pedido> Model = new Tuple<Ventas, Pedido>(Venta, new Pedido());
           
            return View(Model);
        }

        public async Task<IActionResult> SetVentas([Bind(Prefix = "Item1")] Ventas venta1)
        {
            var _venta = await context.Venta.FindAsync(venta1.IdVenta);
         
            if (_venta == null)
            {
                context.Add(venta1);
                await context.SaveChangesAsync();
          
            }
            else
            {
                _venta.IdCliente = venta1.IdCliente;
                _venta.IdTipo = venta1.IdTipo;
                await context.SaveChangesAsync();
            }

            res.resultado = venta1.IdVenta;
            res.estado = true;
            return Json(res);
        }
        public async Task<IActionResult> SetPedidos([Bind(Prefix = "Item2")] Pedido pedido)
        {
            var Ped = await context.Pedidos.Where(x => x.IdPedido == pedido.IdPedido).AnyAsync();
            var product = await context.Productos.FirstOrDefaultAsync(p => p.IdProducto == pedido.IdProducto);
           
            if(product != null)
            {
                pedido.Total = pedido.PrecioUnitario * pedido.Cantidad;
               product.Stock -= pedido.Cantidad;
            }
            context.Pedidos.Add(pedido);
            await context.SaveChangesAsync();
           
            res.resultado = pedido;
            res.mensaje = "Porducto Agregado Correctamente";
            res.res2 = pedido.IdVenta;// cree un nuevo atributo a la clase Response asi me permite pasarle el id y llamarlo en el return
            return Json(res.res2); //aca en vez de retornar todos los datos Json retornaria solo el id de venta asi me lleva al formulario Modificar donde puedo seguir agregando items
           
           
        }
   

       [HttpGet]
        public async Task<IActionResult>TraerProducto(int id)
        {
            var producto = await context.Productos.FirstOrDefaultAsync(p => p.IdProducto == id);
            if(producto == null)
                return NotFound();
            else
            {
                return Ok(producto);
            }
        }
       
        public async Task<IActionResult> Modificar(int? id)
        {
            var valor = id;
            var _vent = await context.Venta.FindAsync(id);
            var Venta = new Ventas();
            if (_vent != null)
            {
                Venta = _vent;
            }
            var cust = await context.Clientes.ToListAsync();
            var tipo = await context.Tipos.ToListAsync();
            ViewBag.Tipos = tipo;
            ViewBag.Clientes = cust;

            ViewBag.Productos = await context.Productos.Select(x => new { x.IdProducto, NombreProducto = x.Nombre + " - " + x.IdMarcaNavigation.Nombre }).ToListAsync();
            if (id != null)
                ViewBag.Pedido = await context.Pedidos.Include(p => p.IdProductoNavigation).Where(x => x.IdVenta == id.Value).ToListAsync();
            Tuple<Ventas, Pedido> Model = new Tuple<Ventas, Pedido>(Venta, new Pedido());

            return View(Model);
        }
        public async Task<IActionResult> Eliminar(int id)
        {
            var VentDelete = await context.Venta.FindAsync(id);
            var detVent = await context.Pedidos.Where(x => x.IdVenta == id).AnyAsync();
            if (VentDelete == null || detVent )
            {
                return StatusCode(404);
            }
            else
                context.Venta.Remove(VentDelete);
            context.SaveChanges();
            return Redirect("/Ventas/");
        }
      public  Pedido pedido1 { get; set; }
        public async Task<IActionResult> EliminarPedido(int id)
        {
            var detallePedido = await context.Pedidos.FirstOrDefaultAsync(dv => dv.IdPedido == id);
          
            var product = await context.Productos.FirstOrDefaultAsync(p => p.IdProducto == detallePedido.IdProducto);
            if (product != null)
            {
                product.Stock += detallePedido.Cantidad;
                context.Pedidos.Remove(detallePedido);
                
                context.SaveChanges();

            }
            return Redirect("/Ventas/Modificar/"+ detallePedido.IdVenta);
        }
        public Ventas vent { get; set; }
        public async Task<IActionResult> Pagado(int id)
        {
            var ventaPago = await context.Venta.FindAsync(id);

            if(ventaPago != null)
            {
                //ventaPago.IdCliente = vent.IdCliente;
                //ventaPago.IdTipo = vent.IdTipo;
                ventaPago.Pagado = true;
                await context.SaveChangesAsync();
            }

            return Redirect("/Ventas/");
        }

    }
}

SistemaPedidos/SistemaPedidos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Calzados Sol y Luna</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaPedidos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">Calzados Sol y Luna</a>
                <button class="navbar-toggler bg-white" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon text-white"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white " asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Ventas" asp-action="Index">Ventas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Direcciones" asp-action="Index">Entregas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Compras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Reportes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-black">
        <div class="container">
            &copy; 2023 - SistemaPedidos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/TraerProductos.js" asp-append-version="true"></script>
    <script src="~/js/Formato.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>